- hosts: azure
  become: yes
  tasks:
    - name: Copy Azure index.html
      copy:
        src: index-azure.html
        dest: /var/www/html/index.html
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
